### ISSUE TITLE
NFR: Configure analytics/tracking

### ISSUE THREAD

**Issue by DanielaPedrochevd** [hlxsites/vg-macktrucks-sv#8]
Configure analytics/tracking (GTM, FB Pixel if needed, and OneTrust)

**Comment by DanielaPedrochevd** [comment]
We are dependent on the Domains.

**Comment by Gonzalo-CG** [comment]
As agreed with Kannan, we will comment out the OneTrust code for go live, and then add the OneTrust ID afterward when it's available.
